name: flutter_sodium_example
description: Demonstrates how to use the flutter_sodium plugin.
publish_to: 'none'

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  url_launcher: ^5.4.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_sodium:
    path: ../

flutter:
  uses-material-design: true
  assets:
    - lib/samples.dart
  fonts:
    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-Regular.ttf