name: flutter_sodium
description: Flutter bindings for libsodium, a modern, easy-to-use crypto library.
version: 0.9.0
author: First Floor Software <info@firstfloorsoftware.com>
homepage: https://github.com/firstfloorsoftware/flutter_sodium

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  ffi: ^0.1.3
  convert: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    androidPackage: com.firstfloorsoftware.flutter_sodium
    pluginClass: FlutterSodiumPlugin
